Update azure-static-web-apps-brave-bay-05cd57910.yml

diff --git a/.github/workflows/azure-static-web-apps-brave-bay-05cd57910.yml b/.github/workflows/azure-static-web-apps-brave-bay-05cd57910.yml
--- a/.github/workflows/azure-static-web-apps-brave-bay-05cd57910.yml
+++ b/.github/workflows/azure-static-web-apps-brave-bay-05cd57910.yml
@@ -18,8 +18,15 @@ jobs:
       - uses: actions/checkout@v2
         with:
           submodules: true
+      - name: Check for Deployment Token
+        id: check_token
+        run: |
+          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_BAY_05CD57910 }}" ]; then
+            echo "AZURE_STATIC_WEB_APPS_API_TOKEN is missing" && exit 1
+          fi
       - name: Build And Deploy
         id: builddeploy
+        if: success() # Ensures previous step succeeded
         uses: Azure/static-web-apps-deploy@v1
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_BAY_05CD57910 }}
@@ -37,8 +44,15 @@ jobs:
     runs-on: ubuntu-latest
     name: Close Pull Request Job
     steps:
+      - name: Check for Deployment Token
+        id: check_token
+        run: |
+          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_BAY_05CD57910 }}" ]; then
+            echo "AZURE_STATIC_WEB_APPS_API_TOKEN is missing" && exit 1
+          fi
       - name: Close Pull Request
         id: closepullrequest
+        if: success() # Ensures previous step succeeded
         uses: Azure/static-web-apps-deploy@v1
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_BAY_05CD57910 }}
